### ISSUE TITLE
Maybe something's wrong.

### ISSUE THREAD

**Issue by Ivanov-Norton** [MattiaMarchi/Common-factor-GWAS---MR#1]
Do you know that the link you left under this Nature article doesn't seem to be right?
![Screenshot 2024-07-17 114707](https://github.com/user-attachments/assets/46dfc1fd-12ff-43eb-8054-68cf5edfecd9)

**Comment by MattiaMarchi** [comment]
Thanks for pointing this out. The issue is caused by the conversion of the ASCII character "---" to the non-ASCII character "–" in the link. The correct link is https://github.com/MattiaMarchi/Common-factor-GWAS---MR, and it can be found correctly reported in the Reporting Summary at the bottom of the manuscript PDF.

**Comment by Ivanov-Norton** [comment]
Sorry that I hadn't finished reading the whole Reporting Summary, and thanks for the reply!😊
